// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGthzE3qKUG4Iap6KkrSBV4zznBpPNjU',
    appId: '1:621378826404:web:6294f110da4d69beca3631',
    messagingSenderId: '621378826404',
    projectId: 'go-parking-72c6c',
    authDomain: 'go-parking-72c6c.firebaseapp.com',
    storageBucket: 'go-parking-72c6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMpR6B_y6SR7Y2FxIuehnElB04I9uzi0',
    appId: '1:621378826404:android:e8bb2f5c770e3f2cca3631',
    messagingSenderId: '621378826404',
    projectId: 'go-parking-72c6c',
    storageBucket: 'go-parking-72c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-oqYNEH7yUAzhBlEVUKVZuL_-iSBjjpU',
    appId: '1:621378826404:ios:01c06de18fbeb033ca3631',
    messagingSenderId: '621378826404',
    projectId: 'go-parking-72c6c',
    storageBucket: 'go-parking-72c6c.firebasestorage.app',
    iosBundleId: 'com.example.whereDidIPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-oqYNEH7yUAzhBlEVUKVZuL_-iSBjjpU',
    appId: '1:621378826404:ios:01c06de18fbeb033ca3631',
    messagingSenderId: '621378826404',
    projectId: 'go-parking-72c6c',
    storageBucket: 'go-parking-72c6c.firebasestorage.app',
    iosBundleId: 'com.example.whereDidIPark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXGthzE3qKUG4Iap6KkrSBV4zznBpPNjU',
    appId: '1:621378826404:web:bdbbc58bcd1e8ea3ca3631',
    messagingSenderId: '621378826404',
    projectId: 'go-parking-72c6c',
    authDomain: 'go-parking-72c6c.firebaseapp.com',
    storageBucket: 'go-parking-72c6c.firebasestorage.app',
  );
}
